# Site settings
title: Learning Three.js
email: jerome.etienne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://learningthreejs.com" # the base hostname & protocol for your site
author: <a href='http://twitter.com/andraconnect' target='_blank'>Alexandra Etienne</a> and <a href='http://twitter.com/jerome_etienne' target='_blank'>Jerome Etienne</a>
permalink: /blog/:year/:month/:day/:title/


category_dir: blog/categories

# Google Analytics
google_analytics_tracking_id: UA-4037844-19

# Build settings
# markdown: kramdown

# from http://ajoz.github.io/2014/06/29/i-want-my-github-flavored-markdown/
# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
